import enum
from typing import Final


class EventTypes(str, enum.Enum):
    MESSAGE_CREATE: Final[str] = "MESSAGE_CREATE"
    MESSAGE_DELETE: Final[str] = "MESSAGE_DELETE"
    MESSAGE_UPDATE: Final[str] = "MESSAGE_UPDATE"
    MESSAGE_REACTION_ADD: Final[str] = "MESSAGE_REACTION_ADD"
    MESSAGE_REACTION_REMOVE: Final[str] = "MESSAGE_REACTION_REMOVE"
    GUILD_CREATE: Final[str] = "GUILD_CREATE"
    GUILD_DELETE: Final[str] = "GUILD_DELETE"
    READY_EVENT: Final[str] = "READY"
    INTERACTION_CREATE: Final[str] = "INTERACTION_CREATE"
    VOICE_STATE_UPDATE: Final[str] = "VOICE_STATE_UPDATE"
    VOICE_SERVER_UPDATE: Final[str] = "VOICE_SERVER_UPDATE"
    CHANNEL_CREATE: Final[str] = "CHANNEL_CREATE"
