import enum


class EventTypes(str, enum.Enum):
    MESSAGE_CREATE = "MESSAGE_CREATE"
    MESSAGE_DELETE = "MESSAGE_DELETE"
    MESSAGE_UPDATE = "MESSAGE_UPDATE"
    MESSAGE_REACTION_ADD = "MESSAGE_REACTION_ADD"
    GUILD_CREATE = "GUILD_CREATE"
    GUILD_DELETE = "GUILD_DELETE"
    READY_EVENT = "READY"
